### ISSUE TITLE
Use of BUILD_SHARED_LIBS (mostly for windows)

### ISSUE THREAD

**Issue by Hippocrates** [wdas/ptex#22]
Have you considered using the standard CMake option `BUILD_SHARED_LIBS` to control whether a static or dynamic library is generated? I'm perhaps speaking from a slightly windows-centric point of view, but it causes problems when building since the export library from the dynamic build will always just overwrite the static library file. 

It also seems like there is some scattershot internally regarding which target is used, where the dynamic target is used for the tests, but the static target is used for the utilities (this, in spite of the fact that both are declared with `-DPTEX_STATIC`). Having the option to select how the tests/utilities are built might be nice.

I can make a PR to demonstrate these ideas if you're interested. It would be fairly minimal in terms of changes, I just don't want to seem like I'm imposing on your library or anything.

**Comment by davvid** [comment]
I think we'd be okay with a PR related to this as long as the resulting set of generated files is unchanged. IIRC, we have it setup to build both static and shared libraries in tandem, within a single build pass.

We build the utilities with the static lib so that they do not necessitate the installation of the dynamic library. That's intentional.

**Comment by davvid** [comment]
Please reopen this issue if this is still a concern.  We now have two cmake options that you can toggle -- `PTEX_BUILD_SHARED_LIBS` and `PTEX_BUILD_STATIC_LIBS`.  If you think we should rename these options to drop the `PTEX_` prefix that should be fine to include in a PR.  Those names are historical and there's no reason why they couldn't be renamed.
