### ISSUE TITLE
Tag a version so Homebrew can update

### ISSUE THREAD

**Issue by lgritz** [wdas/ptex#23]
The current Ptex version that Homebrew installs, tag v2.1.10, does not install PtexVersion.h because it's prior to the Jan 5 commit by Brent that added it to the install list (aside: you should also update the README that lists header files).

If you tag a new release that includes that, somebody will probably update Homebrew so that it installs a usable release.

**Comment by brentb** [comment]
Pushed v2.1.28 for latest commit.

**Comment by lgritz** [comment]
Thanks!

I don't know who maintains the Homebrew recipe, but hopefully he or she follows the GH updates closely enough to update at some point.
