### ISSUE TITLE
Talos Security Advisory for PTEX (TALOS-2018-0515)

### ISSUE THREAD

**Issue by regiwils** [wdas/ptex#30]
Hello, 

The Cisco Talos team found a security vulnerability impacting Walt Disney Per-Face Texture (PTEX)  customers. As this is a sensitive security issue, we request an email address along with PGP.  If PGP is unavailable, please confirm we have correct repository for reporting security issues.

For further information about the Cisco Vendor Vulnerability Reporting and Disclosure Policy please refer to this document which also links to our public PGP key. http://www.cisco.com/web/about/security/psirt/vendor_vulnerability_policy.html

Please CC vulndev@cisco.com on all correspondence related to this issue

**Comment by davvid** [comment]
Oops, sorry I just noticed we still had this issue open.  This was addressed in an earlier release, so closing now.  Thanks again for your report.
