### ISSUE TITLE
zlib API bleeds through header

### ISSUE THREAD

**Issue by bfloch** [wdas/ptex#40]
`PTexReader.h` includes `zlib.h` for the `z_stream_s` member but this also has the side-effect of leaving symbols in other libraries for no reason.

Compare:
https://github.com/PixarAnimationStudios/USD/issues/790

**Comment by brentb** [comment]
PtexReader.h is not part of the public API (applications are expected to go through Ptexture::open or PtexCache::get) so I'm not sure how PtexReader.h is causing problems.
There's no problem with including zlib.h and using z_stream_s in the implementation, is there?

**Comment by bfloch** [comment]
Hi, thanks for the quick reply. Yes you are right.
I was to quick to jump to that conclusion based on Usd's dependencies on zlib.

I'll have to keep looking.
