### ISSUE TITLE
license confusion

### ISSUE THREAD

**Issue by chenrui333** [wdas/ptex#50]
👋 When I was checking the license in the repo. I found two different licenses got referenced in two places.

https://github.com/wdas/ptex/blob/master/Ptex.spec.in#L7 says Apache
https://github.com/wdas/ptex/blob/master/src/doc/License.txt says BSD 

This might also be related to the old issue, #27

cc @SeekingMeaning @Rylan12

**Comment by davvid** [comment]
@chenrui333  I mistakenly copied the spec file over from a different project.  See #51.

**Comment by chenrui333** [comment]
Sounds good, thanks @davvid!
