### ISSUE TITLE
Please add versioning on .so files

### ISSUE THREAD

**Issue by luyatshimbalanga** [wdas/ptex#54]
Will it be possible to include a versioning for .so file like libPtex.so.0 for example? See the build result for rpm package on: https://download.copr.fedorainfracloud.org/results/luya/blender-egl/fedora-rawhide-x86_64/01694327-ptex/builder-live.log.gz

Thanks in advance.

**Comment by luyatshimbalanga** [comment]
Below is the patch

# 0001-set-SOVERSION.patch
diff -up ptex-2.3.2/src/ptex/CMakeLists.txt.orig
ptex-2.3.2/src/ptex/CMakeLists.txt
--- ptex-2.3.2/src/ptex/CMakeLists.txt.orig     2019-03-08 18:39:47.000000000
+0100
+++ ptex-2.3.2/src/ptex/CMakeLists.txt  2020-11-07 11:12:18.517114444 +0100
@@ -32,7 +32,10 @@ endif()

 if(PTEX_BUILD_SHARED_LIBS)
     add_library(Ptex_dynamic SHARED ${SRCS})
-    set_target_properties(Ptex_dynamic PROPERTIES OUTPUT_NAME Ptex)
+    set_target_properties(Ptex_dynamic
+      PROPERTIES
+          OUTPUT_NAME Ptex
+           SOVERSION ${PTEX_MAJOR_VERSION}.${PTEX_MINOR_VERSION})
     target_include_directories(Ptex_dynamic
         PUBLIC
             $<INSTALL_INTERFACE:${CMAKE_INSTALL_INCLUDEDIR}>
===============================================================

**Comment by davvid** [comment]
I'll take a look at this.  It's similar to what we're about to do for partio.  We'll probably track the ptex major version as the SOVERSION.

**Comment by luyatshimbalanga** [comment]
Thank you for look at the patch and the other one for partio.
