### ISSUE TITLE
Build error : unknown target 'doc'

### ISSUE THREAD

**Issue by johhnry** [wdas/ptex#58]
Hi,

I am building ptex on Pop!_OS with the following commands : 

```
make prefix=$PWD/install
make test
make install
make doc
```

But there's no target `doc` : 

```
ninja: error: unknown target 'doc', did you mean 'all'?
make: *** [Makefile:67: doc] Error 1
```

Does the readme needs to be updated?

Thanks

**Comment by davvid** [comment]
I suspect that perhaps you don't have `doxygen` installed, so the `doc` component disabled itself.

Let me know if that's what you hit.  IIRC Pop! is a Debian derivative, so you can try doing `sudo apt install doxygen graphviz` to get the doc dependencies installed.

It looks like the readme mentions this already, but maybe you didn't catch it?  Please reopen if that's not it.

The output from `make` after running `rm -r ./build` might have some clues as well.  Hope that helps!

**Comment by johhnry** [comment]
Hi,

Thanks it worked after installing `doxygen` and deleting the build directory.
