### ISSUE TITLE
Not able to build PTEX on FreeBSD

### ISSUE THREAD

**Issue by michaelcw02** [wdas/ptex#72]
Hi, 

I'm currently trying to use PBRT v3 on several operating systems and one of them is FreeBSD. While trying to install PBRT I found an issue with the following error: 

```
/ptex/src/ptex/PtexPlatform.h:73:10: faltal error: 'alloca.h' file not found
#include <alloca.h>

1 error generated.
*** Error code 1

Stop.
make[2]: stopped in /ptex/build
*** Error code 1

Stop.
make[1]: stopped in /ptex/build
*** Error code 1

Stop.
make: stopped in /ptex/build
```

While troubleshooting, I found the following change in FreeBSD ports: [https://cgit.freebsd.org/ports/commit/?id=5c793405d0e9f0aa05553a2888d6e31b1a17edb1](https://cgit.freebsd.org/ports/commit/?id=5c793405d0e9f0aa05553a2888d6e31b1a17edb1)

These were the specific changes that worked for me: 

- [PtexPlatform.h](https://cgit.freebsd.org/ports/diff/graphics/ptex/files/patch-src_ptex_PtexPlatform.h?id=5c793405d0e9f0aa05553a2888d6e31b1a17edb1)
- [PtexWriter.cpp](https://cgit.freebsd.org/ports/diff/graphics/ptex/files/patch-src_ptex_PtexWriter.cpp?id=5c793405d0e9f0aa05553a2888d6e31b1a17edb1)

**Comment by michaelcw02** [comment]
I'm proposing a solution that worked for me.

**Comment by davvid** [comment]
Thanks for the heads-up. I'd be in favor of having ifdefs in that file to help with BSD compatibility. If you submit a PR I'll be happy to review the changes.

I don't have a FreeBSD install handy so I can't test the build but the guards around alloca.h seem harmless to me.
