### ISSUE TITLE
Update release

### ISSUE THREAD

**Issue by gonsolo** [wdas/ptex#80]
Hi!

Could you release again?
2.4.2 is almost two years old.
Also it's missing the pkgconfig files.

**Comment by davvid** [comment]
Thanks for the ping @gonsolo, much appreciated. I've tagged v2.4.3.

**Comment by gonsolo** [comment]
> Thanks for the ping @gonsolo, much appreciated. I've tagged v2.4.3.

I have to thank you. :)


-- 
g
